### ISSUE TITLE
Size mismatch when evluating world model

### ISSUE THREAD

**Issue by mamengyiyi** [eloialonso/iris#14]
Hi, I run your codes on using `python src/main.py env.train.id=BreakoutNoFrameskip-v4 common.device=cuda:0`. However, I encountered following issue when evaluating the world model for the first time:
![image](https://github.com/eloialonso/iris/assets/23417331/a530e48f-6970-4403-924e-9f9128906bae)
Could you please help me fix this problem?

**Comment by eloialonso** [comment]
Hi, we did not face this issue. Can you share your modifications to the code if any?

**Comment by mamengyiyi** [comment]
> Hi, we did not face this issue. Can you share your modifications to the code if any?

Thanks for your reply! The only modifications are reducing the default `batch_num_samples` of tokenizer, world model and actor_critic to 64, 32 and 32. It's strange that when I rerun the codes, this issue disappear. I will report it here if I encounter it again in the future.
