### ISSUE TITLE
About the study restart function

### ISSUE THREAD

**Issue by tatematsu123** [eloialonso/iris#17]
I would like to restart an interrupted training using the following code in src/trainer.py.
```
if cfg.common.resume:.
    self.load_checkpoint()
```

What directory and what command should I type to use this function?

I have changed cfg.common.resume to true in outputs/YYYYY-MM-DD/hh-mm-ss/ and I run python src/main.py env.train.id=BreakoutNoFrameskip-v4 common.device=cuda:0 wandb.mode=online, but I got an error.

**Comment by eloialonso** [comment]
You just need to run `./scripts/resume.sh` in the run folder `outputs/YYYY-MM-DD/hh-mm-ss/`. 

I hope that helps!

**Comment by tatematsu123** [comment]
Thank you!
