### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by robjlyons** [eloialonso/iris#2]
Hi, what are the systems requirements for this?

I'm using a 3070Ti and am running out of cuda memory.

Thanks,

**Comment by vmicheli** [comment]
Hey, the default configuration should require around 34 GB of memory. You can reduce the memory requirements by decreasing the batch size `batch_num_samples` and increasing the number of gradient accumulation steps `grad_acc_steps` in `config/trainer.yaml`.
