### ISSUE TITLE
please gab code (delta-IRIS )

### ISSUE THREAD

**Issue by wassname** [eloialonso/iris#20]
Hey Eloi, your [delta-IRIS](https://openreview.net/forum?id=o8IDoZggqO) idea seems nice. A concrete improvement in the largest limitation of IRIS. I'm sure you've improved other parts of the code. Do you mind please uploading the code? Even just messy code to a branch

After reading your IRIS delta poster/paper, I wodner if you've considered running it for 1M steps so you can contriute to the crafter benchmark?

**Comment by eloialonso** [comment]
Hey @wassname, thanks for your interest! We are working on a code release for delta-IRIS, it should be out in the next couple of months. We will also include results for Crafter 1M.

**Comment by wassname** [comment]
Looking forward to it!

I've been [experimenting with replacing](https://github.com/wassname/iris_bigvae/tree/borrow_vocab) the dynamics model with a pretrained LLM btw. But it's a negative result:
- it makes the imagination stage slow
- the model doesn't seem to generalize from text to dynamics, there is no continuity between imagines frames

**Comment by eloialonso** [comment]
Interesting, thanks for sharing your experiment!

**Comment by wassname** [comment]
> Hey @wassname, thanks for your interest! We are working on a code release for delta-IRIS, it should be out in the next couple of months. We will also include results for Crafter 1M.

You're probably very busy, but at least one person (me) is still keen to see this! 

In the mean time here are some interesting developments:
- [phi-3 vision](https://huggingface.co/MBZUAI/LLaVA-Phi-3-mini-4k-instruct-lora)
- [craftax](https://github.com/MichaelTMatthews/Craftax) and new environment derived from Crafter that is much faster, has a text rendering mode, and a range of acheivements from easy to hard
