### ISSUE TITLE
How to reproduce the results of IRIS?

### ISSUE THREAD

**Issue by qiwang067** [eloialonso/iris#21]
Hi, Alonso, thank you for providing the detailed code. I want to reproduce the results of IRIS (https://github.com/eloialonso/iris/blob/main/results/data/IRIS.json), but didn't find the corresponding code.

**Comment by eloialonso** [comment]
Hi, 

As explained in the [README](https://github.com/eloialonso/iris/blob/main/README.md), you have to clone the repo, [set up the dependencies](https://github.com/eloialonso/iris?tab=readme-ov-file#setup), and then [launch a training run](https://github.com/eloialonso/iris?tab=readme-ov-file#launch-a-training-run) to reproduce the results for a given game.

Hope that helps!
