### ISSUE TITLE
Regarding the game-specific detailed configurations

### ISSUE THREAD

**Issue by rzbsys** [eloialonso/iris#25]
Hi there,

Really enjoyed reading your paper as well as the codes. Thanks!

I was wondering if I can get the detailed configurations for each game in the Atari environement.
For example, we noticed that in the atari environment, we can manually set the "frame-skip", and "noop-max" values and etc.
In your default configuration, they are set to 4 and 30 respectively, but I was wondering if this value is consistent throughout all the environments in your experimental settings.

Also, did you enable "clip_reward" for all your games (experiments)?

I looked extensively in your paper's supplementary part (appendices) as well as the code, but some of the details to replicate the experimental results are missing it seems.

If there is any other literature (paper) that has disclosed such configurations, I would appreciate if you could share such resource as well.

Thank you!

**Comment by vmicheli** [comment]
Hey,

Thanks for the kind words!

We use the [default configuration](https://github.com/eloialonso/iris/blob/ac6be401fed2b6176c9ce0cf1dc10e376c9d740d/config/trainer.yaml) for the whole benchmark.

We classify rewards as -1/0/+1 but we do not use an environment wrapper for that. See https://github.com/eloialonso/iris/blob/ac6be401fed2b6176c9ce0cf1dc10e376c9d740d/src/models/world_model.py#L120

Hope that helps.
