### ISSUE TITLE
stucking when running `pip install gym[accept-rom-license]==0.21.0`

### ISSUE THREAD

**Issue by maguro27** [eloialonso/iris#7]
Hi.
Thank you for your great work!
Unfortunately, the `pip install gym[accept-rom-license]==0.21.0` script stucks after getting the message `Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... -`.

How can I solve it?
Thanks.

**Comment by vmicheli** [comment]
Hey, thanks for the kind words! The package is installed without any issues on our end. What is your OS and its version? Which pip version are you using, in a virtual environment?

**Comment by maguro27** [comment]
Thank you for getting back to me.
My environment is as follows,

> OS: CentOS 7.5 and Red Hat Enterprise Linux 8.2
> virtual env: anaconda 4.10.3
> python: 3.8
> pip: 22.3.1

**Comment by vmicheli** [comment]
Hey, we cannot reproduce your exact setup but it seems reasonable. However, your issue does not lie within our codebase and I would recommend that you take a look at potential problems encountered when installing gym.

**Comment by vmicheli** [comment]
Follow-up discussion https://github.com/openai/gym/issues/3170 with solution https://github.com/openai/gym/issues/3170#issuecomment-1427040869. This might also be of interest: https://github.com/openai/gym/issues/3176
